# Generated by Django 5.1 on 2024-08-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About uS'},
        ),
        migrations.AlterModelOptions(
            name='aboutusgallery',
            options={'verbose_name': 'About us Gallery', 'verbose_name_plural': 'About us Galleries'},
        ),
    ]
