# Generated by Django 5.1 on 2024-08-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_contacts_contact_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='aboutusgallery',
            options={'verbose_name': 'About Us Gallery', 'verbose_name_plural': 'About Us Galleries'},
        ),
        migrations.AlterModelOptions(
            name='contactwithus',
            options={'verbose_name': 'Contact With Us', 'verbose_name_plural': 'Contact With Us'},
        ),
    ]
